export const lightTheme = {
  colors: {
    primaryBackground: '#fff',
    primaryText: '#000',
    statisticText: '#fff',
    secondaryText: '#fff',
    acentColor: '#fac507',
    logoColor: '#fff',
    logoBackground: '#000',
    iconColor: '#000',
    modalBackdropColor: 'rgba(0, 0, 0, 0.5)',
    logoText: '#000',
    switcherBackground: '#000',
    balanceBackground: '#124720',
    itemsBackground: '#000',
    itemsText: '#fff',
    hoverColor: '#0cc9eb',
    themeSwitcerHoverColor: '#fac507',
    activeLink: '#fac507',
    bwInverted: '#000',
  },
  breakpoints: {
    mobileS: '320px',
    mobileM: '480px',
    tablet: '768px',
    desktop: '1000px',
    desktopL: '1200px',
  },
  borders: {
    sectionsHeader: '1px solid #000',
  },
  fontSizes: {
    xs: '8px',
    s: '12px',
    sm: '14px',
    m: '16px',
    ml: '18px',
    l: '20px',
    xl: '24px',
    xxl: '30px',
  },
  radii: {
    none: '0',
    xs: '4px',
    s: '5px',
    sm: '8px',
    m: '10px',
    ml: '16px',
    l: '20px',
    xl: '24px',
    round: '50%',
  },
};

export const darkTheme = {
  colors: {
    primaryBackground: '#232b47',
    primaryText: '#fff',
    statisticText: '#fff',
    secondaryText: '#000',
    acentColor: '#0cc9eb',
    logoColor: '#fff',
    logoBackground: '#000',
    iconColor: '#fff',
    modalBackdropColor: 'rgba(255, 255, 255, 0.5)',
    logoText: '#000',
    switcherBackground: '#000',
    balanceBackground: '#124720',
    itemsBackground: '#000',
    itemsText: '#fff',
    hoverColor: '#fac507',
    themeSwitcerHoverColor: '#0cc9eb',
    activeLink: '#fac507',
    bwInverted: '#fff',
  },
  breakpoints: {
    mobileS: '320px',
    mobileM: '480px',
    tablet: '768px',
    desktop: '1000px',
    desktopL: '1200px',
  },
  borders: {
    sectionsHeader: '1px solid #fff',
  },
  fontSizes: {
    xs: '8px',
    s: '12px',
    sm: '14px',
    m: '16px',
    ml: '18px',
    l: '20px',
    xl: '24px',
    xxl: '30px',
  },
  radii: {
    none: '0',
    xs: '4px',
    s: '5px',
    sm: '8px',
    m: '10px',
    ml: '16px',
    l: '20px',
    xl: '24px',
    round: '50%',
  },
};
